-- Canonical generic industrial test suite.
-- ID conventions used here:
--   DG_EDGE___SUFFIX__      = test DeviceGroup (edge/control cell)
--   VIRTUAL_PLC___SUFFIX__  = test PLC / controller
--   DRV_EDGE___SUFFIX__     = test drive / inverter
--   GW_EDGE___SUFFIX__      = test moqui-device-gateway instance
-- This SQL fixture mirrors the Moqui XML seed in
-- moqui-framework/runtime/component/moqui-device/data/DeviceTestData.xml.

INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DgmpEdgeGateway', 'DeviceGroupMemberPurpose', 'Edge Gateway')
ON CONFLICT (ENUM_ID) DO NOTHING;
INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DgmpProcessPLC', 'DeviceGroupMemberPurpose', 'Process PLC')
ON CONFLICT (ENUM_ID) DO NOTHING;
INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DrrMoquiDeviceGateway', 'DeviceRequestRouter', 'Moqui Device Gateway')
ON CONFLICT (ENUM_ID) DO NOTHING;
INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DrtCyclic', 'DeviceRequestType', 'Cyclic Subscription Request')
ON CONFLICT (ENUM_ID) DO NOTHING;

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('GW_EDGE___SUFFIX__', 'DtEdgeGateway');
INSERT INTO PHYSICAL_DEVICE (DEVICE_ID, DEVICE_NAME)
VALUES ('GW_EDGE___SUFFIX__', 'Gateway Edge __SUFFIX__');

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('VIRTUAL_PLC___SUFFIX__', 'DtPLC');
INSERT INTO PHYSICAL_DEVICE (DEVICE_ID, DEVICE_NAME)
VALUES ('VIRTUAL_PLC___SUFFIX__', 'Virtual PLC __SUFFIX__');

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('DRV_EDGE___SUFFIX__', 'DtDrive');
INSERT INTO PHYSICAL_DEVICE (DEVICE_ID, DEVICE_NAME)
VALUES ('DRV_EDGE___SUFFIX__', 'Drive Edge __SUFFIX__');

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('DG_EDGE___SUFFIX__', 'DgtControl');
INSERT INTO DEVICE_GROUP (DEVICE_ID, GROUP_NAME)
VALUES ('DG_EDGE___SUFFIX__', 'Test Cell Group __SUFFIX__');
INSERT INTO DEVICE_GROUP_MEMBER (DEVICE_ID, MEMBER_DEVICE_ID, PURPOSE_ENUM_ID, SEQUENCE_NUM, STATUS_ID)
VALUES ('DG_EDGE___SUFFIX__', 'GW_EDGE___SUFFIX__', 'DgmpEdgeGateway', 1, 'DgmsAlive');
INSERT INTO DEVICE_GROUP_MEMBER (DEVICE_ID, MEMBER_DEVICE_ID, PURPOSE_ENUM_ID, SEQUENCE_NUM, STATUS_ID)
VALUES ('DG_EDGE___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DgmpProcessPLC', 2, 'DgmsAlive');
INSERT INTO DEVICE_GROUP_MEMBER (DEVICE_ID, MEMBER_DEVICE_ID, PURPOSE_ENUM_ID, SEQUENCE_NUM, STATUS_ID)
VALUES ('DG_EDGE___SUFFIX__', 'DRV_EDGE___SUFFIX__', 'DgmpDrive', 3, 'DgmsAlive');

INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestCellHeartbeatDef___SUFFIX__', 'PtNumberInteger', 'CELL-__SUFFIX__-01', 'Test Cell Heartbeat');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('TestCellHeartbeatParam___SUFFIX__', 'TestCellHeartbeatDef___SUFFIX__', 'DG_EDGE___SUFFIX__', 1000);

INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestDriveSpeedSetpointDef___SUFFIX__', 'PtNumberInteger', 'DRV-__SUFFIX__-01', 'Drive Speed Setpoint');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestDriveTorqueLimitDef___SUFFIX__', 'PtNumberInteger', 'DRV-__SUFFIX__-02', 'Drive Torque Limit');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('TestDriveSpeedSetpointParam___SUFFIX__', 'TestDriveSpeedSetpointDef___SUFFIX__', 'DRV_EDGE___SUFFIX__', 1500);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('TestDriveTorqueLimitParam___SUFFIX__', 'TestDriveTorqueLimitDef___SUFFIX__', 'DRV_EDGE___SUFFIX__', 180);

INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcReferenceDef___SUFFIX__', 'PtNumberDecimal', 'PLC-__SUFFIX__-24.01', 'Reference');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcFeedbackDef___SUFFIX__', 'PtNumberDecimal', 'PLC-__SUFFIX__-24.02', 'Feedback');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcMainControlWordDef___SUFFIX__', 'PtTextShort', 'PLC-__SUFFIX__-24.03', 'MainControlWord');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcMainStatusWordDef___SUFFIX__', 'PtTextShort', 'PLC-__SUFFIX__-24.04', 'MainStatusWord');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcFaultDef___SUFFIX__', 'PtTextIndicator', 'PLC-__SUFFIX__-24.05', 'Fault');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcRecipeReferenceDef___SUFFIX__', 'PtNumberDecimal', 'PLC-__SUFFIX__-24.11', 'RecipeReference');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('TestPlcRecipeStateDef___SUFFIX__', 'PtTextShort', 'PLC-__SUFFIX__-24.12', 'RecipeState');

INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('TestPlcReferenceParam___SUFFIX__', 'TestPlcReferenceDef___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 300.00);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('TestPlcFeedbackParam___SUFFIX__', 'TestPlcFeedbackDef___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 300.03);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, SYMBOLIC_VALUE)
VALUES ('TestPlcMainControlWordParam___SUFFIX__', 'TestPlcMainControlWordDef___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'START');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, SYMBOLIC_VALUE)
VALUES ('TestPlcMainStatusWordParam___SUFFIX__', 'TestPlcMainStatusWordDef___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'READY');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, SYMBOLIC_VALUE)
VALUES ('TestPlcFaultParam___SUFFIX__', 'TestPlcFaultDef___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'N');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, BROKER_URI, ONLY_CHANGED_PARAMETERS)
VALUES ('TestPlcMqttPublishReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtWrite', 'DrpControl', 'DrrMoquiDeviceGateway', '__MQTT_PUBLISH_BASE_URI__', 'N');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, REQUEST_ITEM_NAME, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcMqttPublishReq___SUFFIX__', 'TestPlcReferenceParam___SUFFIX__', 'reference', 1, 'mqtt-write-device-request/virtual-plc/reference');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, REQUEST_ITEM_NAME, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcMqttPublishReq___SUFFIX__', 'TestPlcMainControlWordParam___SUFFIX__', 'mainControlWord', 2, 'mqtt-write-device-request/virtual-plc/main-control-word');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, BROKER_URI, POLLING_INTERVAL)
VALUES ('TestPlcMqttSubscribeReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtCyclic', 'DrpControl', 'DrrMoquiDeviceGateway', '__MQTT_SUBSCRIBE_BASE_URI__', 100);
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcMqttSubscribeReq___SUFFIX__', 'TestPlcFeedbackParam___SUFFIX__', 1, 'mqtt-subscribe-device-request/virtual-plc/feedback');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcMqttSubscribeReq___SUFFIX__', 'TestPlcFaultParam___SUFFIX__', 2, 'mqtt-subscribe-device-request/virtual-plc/fault');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, PARENT_REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, BROKER_URI)
VALUES ('TestPlcMqttUnsubscribeReq___SUFFIX__', 'TestPlcMqttSubscribeReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtUnsubscribe', 'DrpControl', 'DrrMoquiDeviceGateway', '__MQTT_SUBSCRIBE_BASE_URI__');

INSERT INTO DEVICE_CONFIG (DEVICE_CONFIG_ID, CONFIG_NAME, CONFIG_TYPE_ENUM_ID, PURPOSE_ENUM_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('TestPlcGatewayConfig1___SUFFIX__', 'Test PLC Gateway Config', 'DctApplyConfig', 'DcpRunConfig', 'DtPLC');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_CONFIG_ID, NUMERIC_VALUE)
VALUES ('TestPlcRecipeReferenceCfgParam___SUFFIX__', 'TestPlcRecipeReferenceDef___SUFFIX__', 'TestPlcGatewayConfig1___SUFFIX__', 250.0);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_CONFIG_ID, SYMBOLIC_VALUE)
VALUES ('TestPlcRecipeStateCfgParam___SUFFIX__', 'TestPlcRecipeStateDef___SUFFIX__', 'TestPlcGatewayConfig1___SUFFIX__', 'AUTO');

INSERT INTO DEVICE_RULE_SET (DEVICE_RULE_SET_ID, RULE_SET_NAME, PURPOSE_ENUM_ID, DEVICE_ID)
VALUES ('TestPlcGatewayRuleSet1___SUFFIX__', 'TestPlcGatewayRuleSet', 'DrspProcess', 'VIRTUAL_PLC___SUFFIX__');
INSERT INTO DEVICE_RULE (DEVICE_RULE_ID, DEVICE_RULE_SET_ID, DEVICE_CONFIG_ID, DEVICE_ID, RULE_TYPE_ENUM_ID, RULE_NAME, PRIORITY)
VALUES ('TestPlcGatewayRule010___SUFFIX__', 'TestPlcGatewayRuleSet1___SUFFIX__', 'TestPlcGatewayConfig1___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtApplyConfig', 'Apply Test PLC gateway config', 1);

-- -----------------------------------------------------------------------------
-- Trajectory export seed data
-- 2 waypoints, 3 Cartesian dimensions each (X/Y/Z)
-- pt[0]: normal blending (no override), pt[1]: isBreakPoint exact stop
-- -----------------------------------------------------------------------------
INSERT INTO APPROXIMATED_FUNCTION
    (APPROXIMATED_FUNCTION_ID, INTERPOLATION_ENUM_ID, PURPOSE_ENUM_ID, VECTOR_SPACE_ENUM_ID, CODOMAIN_TYPE_ENUM_ID, PARAMETRIZATION_DEGREE, DATA_STORAGE_ENUM_ID, NAME)
VALUES
    ('TestPlcTrajectory01___SUFFIX__', 'AfiPiecewise', 'AfpTrajectory', 'EuclideanSpace3D', 'AfctVector', 1, 'AfdsPointTable', 'Test PLC Trajectory');

INSERT INTO PARAMETRIC_PATH
    (APPROXIMATED_FUNCTION_ID, PROFILE_ENUM_ID)
VALUES
    ('TestPlcTrajectory01___SUFFIX__', 'PppfTrajectoryProfile');

INSERT INTO TRAJECTORY
    (APPROXIMATED_FUNCTION_ID)
VALUES
    ('TestPlcTrajectory01___SUFFIX__');

INSERT INTO VECTOR (VECTOR_ID) VALUES ('VEC_PT1___SUFFIX__');
INSERT INTO VECTOR (VECTOR_ID) VALUES ('VEC_PT2___SUFFIX__');

INSERT INTO APPROXIMATED_FUNCTION_SAMPLE
    (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, SAMPLE_TYPE_ENUM_ID, SAMPLE_CODE, SAMPLE_NAME, SEQUENCE_NUM, SAMPLE_VECTOR_ID)
VALUES
    ('TestPlcTrajectory01___SUFFIX__', 'AFS_PT1___SUFFIX__', 'AfstWaypoint', 'WP0001', 'Waypoint 1', 1, 'VEC_PT1___SUFFIX__');
INSERT INTO APPROXIMATED_FUNCTION_SAMPLE
    (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, SAMPLE_TYPE_ENUM_ID, SAMPLE_CODE, SAMPLE_NAME, SEQUENCE_NUM, SAMPLE_VECTOR_ID)
VALUES
    ('TestPlcTrajectory01___SUFFIX__', 'AFS_PT2___SUFFIX__', 'AfstWaypoint', 'WP0002', 'Waypoint 2', 2, 'VEC_PT2___SUFFIX__');

INSERT INTO PARAMETRIC_PATH_POINT
    (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, TOLERANCE)
VALUES
    ('TestPlcTrajectory01___SUFFIX__', 'AFS_PT1___SUFFIX__', 10.0);
INSERT INTO PARAMETRIC_PATH_POINT
    (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, TOLERANCE)
VALUES
    ('TestPlcTrajectory01___SUFFIX__', 'AFS_PT2___SUFFIX__', NULL);

INSERT INTO TRAJECTORY_POINT (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, IS_BREAK_POINT, BLENDING_ENUM_ID, POINT_TIME_OFFSET_MILLIS)
VALUES ('TestPlcTrajectory01___SUFFIX__', 'AFS_PT1___SUFFIX__', 'N', NULL, 500.0);
INSERT INTO TRAJECTORY_POINT (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, IS_BREAK_POINT, BLENDING_ENUM_ID, POINT_TIME_OFFSET_MILLIS)
VALUES ('TestPlcTrajectory01___SUFFIX__', 'AFS_PT2___SUFFIX__', 'Y', NULL, 1000.0);

INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT1___SUFFIX__', 'VC_PT1_0___SUFFIX__', 0, 100.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT1___SUFFIX__', 'VC_PT1_1___SUFFIX__', 1, 200.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT1___SUFFIX__', 'VC_PT1_2___SUFFIX__', 2, 300.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT2___SUFFIX__', 'VC_PT2_0___SUFFIX__', 0, 150.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT2___SUFFIX__', 'VC_PT2_1___SUFFIX__', 1, 250.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT2___SUFFIX__', 'VC_PT2_2___SUFFIX__', 2, 350.0);

INSERT INTO DEVICE_CONFIG (DEVICE_CONFIG_ID, CONFIG_NAME, DEVICE_TYPE_ENUM_ID, APPROXIMATED_FUNCTION_ID)
VALUES ('TestPlcTrajectoryConfig1___SUFFIX__', 'Test PLC Trajectory Config', 'DtPLC', 'TestPlcTrajectory01___SUFFIX__');

INSERT INTO DEVICE_RULE_SET (DEVICE_RULE_SET_ID, RULE_SET_NAME, PURPOSE_ENUM_ID, DEVICE_ID)
VALUES ('TestPlcTrajectoryRuleSet1___SUFFIX__', 'TestPlcTrajectoryRuleSet', 'DrspProcess', 'VIRTUAL_PLC___SUFFIX__');
INSERT INTO DEVICE_RULE (DEVICE_RULE_ID, DEVICE_RULE_SET_ID, DEVICE_CONFIG_ID, DEVICE_ID, RULE_TYPE_ENUM_ID, RULE_NAME, PRIORITY)
VALUES ('TestPlcTrajectoryRule010___SUFFIX__', 'TestPlcTrajectoryRuleSet1___SUFFIX__', 'TestPlcTrajectoryConfig1___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtApplyConfig', 'Apply Test PLC trajectory config', 1);
