INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DgmpEdgeGateway', 'DeviceGroupMemberPurpose', 'Edge Gateway')
ON CONFLICT (ENUM_ID) DO NOTHING;
INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DgmpProcessPLC', 'DeviceGroupMemberPurpose', 'Process PLC')
ON CONFLICT (ENUM_ID) DO NOTHING;
INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DrrMoquiDeviceGateway', 'DeviceRequestRouter', 'Moqui Device Gateway')
ON CONFLICT (ENUM_ID) DO NOTHING;
INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION)
VALUES ('DrtCyclic', 'DeviceRequestType', 'Cyclic Subscription Request')
ON CONFLICT (ENUM_ID) DO NOTHING;

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('GW_EDGE___SUFFIX__', 'DtComputer');
INSERT INTO PHYSICAL_DEVICE (DEVICE_ID, DEVICE_NAME)
VALUES ('GW_EDGE___SUFFIX__', 'gateway_edge');

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('VIRTUAL_PLC___SUFFIX__', 'DtPLC');
INSERT INTO PHYSICAL_DEVICE (DEVICE_ID, DEVICE_NAME)
VALUES ('VIRTUAL_PLC___SUFFIX__', 'virtual_plc');

INSERT INTO DEVICE (DEVICE_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('DG_EDGE___SUFFIX__', 'DtManufacturingCell');
INSERT INTO DEVICE_GROUP (DEVICE_ID, GROUP_NAME)
VALUES ('DG_EDGE___SUFFIX__', 'Edge Gateway Group');
INSERT INTO DEVICE_GROUP_MEMBER (DEVICE_ID, MEMBER_DEVICE_ID, PURPOSE_ENUM_ID, SEQUENCE_NUM, STATUS_ID)
VALUES ('DG_EDGE___SUFFIX__', 'GW_EDGE___SUFFIX__', 'DgmpEdgeGateway', 1, 'DgmsAlive');
INSERT INTO DEVICE_GROUP_MEMBER (DEVICE_ID, MEMBER_DEVICE_ID, PURPOSE_ENUM_ID, SEQUENCE_NUM, STATUS_ID)
VALUES ('DG_EDGE___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DgmpProcessPLC', 2, 'DgmsAlive');

INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_REFERENCE___SUFFIX__', 'PtNumberDecimal', 'VPL-__SUFFIX__-24.01', 'Reference');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_FEEDBACK___SUFFIX__', 'PtNumberDecimal', 'VPL-__SUFFIX__-24.02', 'Feedback');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_MAIN_CONTROL_WORD___SUFFIX__', 'PtTextShort', 'VPL-__SUFFIX__-24.03', 'MainControlWord');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_MAIN_STATUS_WORD___SUFFIX__', 'PtTextShort', 'VPL-__SUFFIX__-24.04', 'MainStatusWord');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_FAULT___SUFFIX__', 'PtTextIndicator', 'VPL-__SUFFIX__-24.05', 'Fault');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_RECIPE_REFERENCE___SUFFIX__', 'PtNumberDecimal', 'VPL-__SUFFIX__-24.11', 'RecipeReference');
INSERT INTO PARAMETER_DEF (PARAMETER_DEF_ID, PARAMETER_TYPE_ENUM_ID, PARAMETER_CODE, PARAMETER_NAME)
VALUES ('VPL_PD_RECIPE_STATE___SUFFIX__', 'PtTextShort', 'VPL-__SUFFIX__-24.12', 'RecipeState');

INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('VPL_PARAM_REFERENCE___SUFFIX__', 'VPL_PD_REFERENCE___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 300.00);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, NUMERIC_VALUE)
VALUES ('VPL_PARAM_FEEDBACK___SUFFIX__', 'VPL_PD_FEEDBACK___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 300.03);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, SYMBOLIC_VALUE)
VALUES ('VPL_PARAM_MAIN_CONTROL_WORD___SUFFIX__', 'VPL_PD_MAIN_CONTROL_WORD___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'START');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, SYMBOLIC_VALUE)
VALUES ('VPL_PARAM_MAIN_STATUS_WORD___SUFFIX__', 'VPL_PD_MAIN_STATUS_WORD___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'READY');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_ID, SYMBOLIC_VALUE)
VALUES ('VPL_PARAM_FAULT___SUFFIX__', 'VPL_PD_FAULT___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'N');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, BROKER_URI, ONLY_CHANGED_PARAMETERS)
VALUES ('VPL_MQTT_PUBLISH_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtWrite', 'DrpControl', 'DrrMoquiDeviceGateway', '__MQTT_PUBLISH_BASE_URI__', 'N');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_MQTT_PUBLISH_REQ___SUFFIX__', 'VPL_PARAM_REFERENCE___SUFFIX__', 1, 'mqtt-write-device-request/virtual-plc/reference');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_MQTT_PUBLISH_REQ___SUFFIX__', 'VPL_PARAM_MAIN_CONTROL_WORD___SUFFIX__', 2, 'mqtt-write-device-request/virtual-plc/main-control-word');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, BROKER_URI, POLLING_INTERVAL)
VALUES ('VPL_MQTT_SUB_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtCyclic', 'DrpControl', 'DrrMoquiDeviceGateway', '__MQTT_SUBSCRIBE_BASE_URI__', 100);
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_MQTT_SUB_REQ___SUFFIX__', 'VPL_PARAM_FEEDBACK___SUFFIX__', 1, 'mqtt-subscribe-device-request/virtual-plc/feedback');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('VPL_MQTT_SUB_REQ___SUFFIX__', 'VPL_PARAM_FAULT___SUFFIX__', 2, 'mqtt-subscribe-device-request/virtual-plc/fault');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, PARENT_REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, BROKER_URI)
VALUES ('VPL_MQTT_UNSUB_REQ___SUFFIX__', 'VPL_MQTT_SUB_REQ___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtUnsubscribe', 'DrpControl', 'DrrMoquiDeviceGateway', '__MQTT_SUBSCRIBE_BASE_URI__');

INSERT INTO DEVICE_CONFIG (DEVICE_CONFIG_ID, CONFIG_NAME, CONFIG_TYPE_ENUM_ID, PURPOSE_ENUM_ID, DEVICE_TYPE_ENUM_ID)
VALUES ('VPL_CONFIG_1___SUFFIX__', 'Virtual PLC Config', 'DctApplyConfig', 'DcpRunConfig', 'DtPLC');
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_CONFIG_ID, NUMERIC_VALUE)
VALUES ('VPL_CFG_PARAM_REFERENCE___SUFFIX__', 'VPL_PD_RECIPE_REFERENCE___SUFFIX__', 'VPL_CONFIG_1___SUFFIX__', 250.0);
INSERT INTO PARAMETER (PARAMETER_ID, PARAMETER_DEF_ID, DEVICE_CONFIG_ID, SYMBOLIC_VALUE)
VALUES ('VPL_CFG_PARAM_STATE___SUFFIX__', 'VPL_PD_RECIPE_STATE___SUFFIX__', 'VPL_CONFIG_1___SUFFIX__', 'AUTO');

INSERT INTO DEVICE_RULE_SET (DEVICE_RULE_SET_ID, RULE_SET_NAME, PURPOSE_ENUM_ID, DEVICE_ID)
VALUES ('VPL_RULESET_1___SUFFIX__', 'VirtualPlcRuleSet', 'DrspProcess', 'VIRTUAL_PLC___SUFFIX__');
INSERT INTO DEVICE_RULE (DEVICE_RULE_ID, DEVICE_RULE_SET_ID, DEVICE_CONFIG_ID, DEVICE_ID, RULE_TYPE_ENUM_ID, RULE_NAME, PRIORITY)
VALUES ('VPL_RULE_1___SUFFIX__', 'VPL_RULESET_1___SUFFIX__', 'VPL_CONFIG_1___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtApplyConfig', 'Apply Virtual PLC Config', 1);

-- -----------------------------------------------------------------------------
-- Trajectory export seed data
-- 2 waypoints, 3 Cartesian dimensions each (X/Y/Z)
-- pt[0]: normal blending (no override), pt[1]: isBreakPoint exact stop
-- -----------------------------------------------------------------------------
INSERT INTO APPROXIMATED_FUNCTION_SAMPLE (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, SEQUENCE_NUM, SAMPLE_VECTOR_ID)
VALUES ('TRJ_TEST_01___SUFFIX__', 'AFS_PT1___SUFFIX__', 1, 'VEC_PT1___SUFFIX__');
INSERT INTO APPROXIMATED_FUNCTION_SAMPLE (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, SEQUENCE_NUM, SAMPLE_VECTOR_ID)
VALUES ('TRJ_TEST_01___SUFFIX__', 'AFS_PT2___SUFFIX__', 2, 'VEC_PT2___SUFFIX__');

INSERT INTO TRAJECTORY_POINT (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, IS_BREAK_POINT, BLENDING_ENUM_ID, POINT_TIME_OFFSET_MILLIS)
VALUES ('TRJ_TEST_01___SUFFIX__', 'AFS_PT1___SUFFIX__', 'N', NULL, 500.0);
INSERT INTO TRAJECTORY_POINT (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, IS_BREAK_POINT, BLENDING_ENUM_ID, POINT_TIME_OFFSET_MILLIS)
VALUES ('TRJ_TEST_01___SUFFIX__', 'AFS_PT2___SUFFIX__', 'Y', NULL, 1000.0);

INSERT INTO PARAMETRIC_PATH_POINT (APPROXIMATED_FUNCTION_ID, APPROXIMATED_FUNCTION_SAMPLE_ID, TOLERANCE)
VALUES ('TRJ_TEST_01___SUFFIX__', 'AFS_PT1___SUFFIX__', 10.0);

INSERT INTO VECTOR (VECTOR_ID) VALUES ('VEC_PT1___SUFFIX__');
INSERT INTO VECTOR (VECTOR_ID) VALUES ('VEC_PT2___SUFFIX__');

INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT1___SUFFIX__', 'VC_PT1_0___SUFFIX__', 0, 100.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT1___SUFFIX__', 'VC_PT1_1___SUFFIX__', 1, 200.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT1___SUFFIX__', 'VC_PT1_2___SUFFIX__', 2, 300.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT2___SUFFIX__', 'VC_PT2_0___SUFFIX__', 0, 150.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT2___SUFFIX__', 'VC_PT2_1___SUFFIX__', 1, 250.0);
INSERT INTO VECTOR_COMPONENT (VECTOR_ID, VECTOR_COMPONENT_ID, DIMENSION_INDEX, REAL_VALUE)
VALUES ('VEC_PT2___SUFFIX__', 'VC_PT2_2___SUFFIX__', 2, 350.0);

INSERT INTO DEVICE_CONFIG (DEVICE_CONFIG_ID, CONFIG_NAME, DEVICE_TYPE_ENUM_ID, APPROXIMATED_FUNCTION_ID)
VALUES ('TRJ_CONFIG_1___SUFFIX__', 'TrajectoryTest', 'DtRobot', 'TRJ_TEST_01___SUFFIX__');

INSERT INTO DEVICE_RULE_SET (DEVICE_RULE_SET_ID, RULE_SET_NAME, PURPOSE_ENUM_ID, DEVICE_ID)
VALUES ('TRJ_RULESET_1___SUFFIX__', 'TrajectoryRuleSet', 'DrspProcess', 'VIRTUAL_PLC___SUFFIX__');
INSERT INTO DEVICE_RULE (DEVICE_RULE_ID, DEVICE_RULE_SET_ID, DEVICE_CONFIG_ID, DEVICE_ID, RULE_TYPE_ENUM_ID, RULE_NAME, PRIORITY)
VALUES ('TRJ_RULE_1___SUFFIX__', 'TRJ_RULESET_1___SUFFIX__', 'TRJ_CONFIG_1___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtApplyConfig', 'Trajectory Config', 1);
