INSERT INTO DEVICE_CONNECTION (CONNECTION_NAME, DEVICE_ID, CONNECTION_TYPE_ENUM_ID, PURPOSE_ENUM_ID, DRIVER_ENUM_ID, TRANSPORT_ENUM_ID, TRANSPORT_CONFIG)
VALUES ('TestPlcOpcUaConn___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DctDirectConnection', 'DcpOperations', 'DcdOpcUa', 'DctrTcp', '__OPCUA_TRANSPORT_CONFIG__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME, POLLING_INTERVAL)
VALUES ('TestPlcOpcUaReadReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtCyclic', 'DrpControl', 'DrrDirect', 'TestPlcOpcUaConn___SUFFIX__', 100);
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcOpcUaReadReq___SUFFIX__', 'TestPlcFeedbackParam___SUFFIX__', 1, '__OPCUA_FEEDBACK_NODE__');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcOpcUaReadReq___SUFFIX__', 'TestPlcFaultParam___SUFFIX__', 2, '__OPCUA_FAULT_NODE__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, PARENT_REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME)
VALUES ('TestPlcOpcUaUnsubscribeReq___SUFFIX__', 'TestPlcOpcUaReadReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtUnsubscribe', 'DrpControl', 'DrrDirect', 'TestPlcOpcUaConn___SUFFIX__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME, ONLY_CHANGED_PARAMETERS)
VALUES ('TestPlcOpcUaWriteReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtWrite', 'DrpControl', 'DrrDirect', 'TestPlcOpcUaConn___SUFFIX__', 'N');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcOpcUaWriteReq___SUFFIX__', 'TestPlcReferenceParam___SUFFIX__', 1, '__OPCUA_REFERENCE_WRITE_NODE__');

INSERT INTO DEVICE_REQUEST (REQUEST_NAME, DEVICE_ID, REQUEST_TYPE_ENUM_ID, PURPOSE_ENUM_ID, ROUTER_ENUM_ID, CONNECTION_NAME)
VALUES ('TestPlcOpcUaOneshotReq___SUFFIX__', 'VIRTUAL_PLC___SUFFIX__', 'DrtRead', 'DrpControl', 'DrrDirect', 'TestPlcOpcUaConn___SUFFIX__');
INSERT INTO DEVICE_REQUEST_ITEM (REQUEST_NAME, PARAMETER_ID, SEQUENCE_NUM, QUERY)
VALUES ('TestPlcOpcUaOneshotReq___SUFFIX__', 'TestPlcFeedbackParam___SUFFIX__', 1, '__OPCUA_FEEDBACK_NODE__');
